title: Urban VitalControl
description: Health management 2.0
time_format_default: 02.01.2006
time_format_blog: 02.01.2006
copyright: Urban GmbH & Co.KG
privacy_policy: https://www.urbanonline.de/en/privacy-policy
taxonomy:
  # set taxonomyCloud: [] to hide taxonomy clouds
  taxonomyCloud:
    - categories
    - tags
  # If used, must have same length as taxonomyCloud
  taxonomyCloudTitle:
    - "Κατηγορίες"
    - "Σύννεφο ετικετών"
  # set taxonomyPageHeader: [] to hide taxonomies on the page headers
  taxonomyPageHeader:
    - categories
    - tags
