title: Urban VitalControl
description: Vesel카bas p훮rvald카ba 2.0
time_format_default: 02.01.2006
time_format_blog: 02.01.2006
copyright: Urban GmbH & Co.KG
privacy_policy: https://www.urbanonline.de/en/privacy-policy
taxonomy:
  # set taxonomyCloud: [] to hide taxonomy clouds
  taxonomyCloud:
    - kategorijas
    - birkas
  # If used, must have same length as taxonomyCloud
  taxonomyCloudTitle:
    - "Kategorijas"
    - "Tag m훮konis"
  # set taxonomyPageHeader: [] to hide taxonomies on the page headers
  taxonomyPageHeader:
    - kategorijas
    - birkas
